"""empty message

Revision ID: 15d3e11dea8e
Revises: 6b70a7ed2a00
Create Date: 2018-07-26 17:44:49.372723

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15d3e11dea8e'
down_revision = '6b70a7ed2a00'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_images_id', table_name='images')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_images_id', 'images', ['id'], unique=1)
    # ### end Alembic commands ###
