"""empty message

Revision ID: 3b4de0bd317c
Revises: 842198a9873c
Create Date: 2018-07-27 09:35:58.132092

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b4de0bd317c'
down_revision = '842198a9873c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images', sa.Column('image_id', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_images_image_id'), 'images', ['image_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_images_image_id'), table_name='images')
    op.drop_column('images', 'image_id')
    # ### end Alembic commands ###
