"""empty message

Revision ID: 842198a9873c
Revises: 15d3e11dea8e
Create Date: 2018-07-26 17:46:08.440657

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '842198a9873c'
down_revision = '15d3e11dea8e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_images_id'), 'images', ['id'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_images_id'), table_name='images')
    # ### end Alembic commands ###
