"""empty message

Revision ID: c38357be8437
Revises: f1bf00fd53f7
Create Date: 2018-07-26 16:13:58.608050

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c38357be8437'
down_revision = 'f1bf00fd53f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images', sa.Column('image_full', sa.String(), nullable=True))
    op.create_index(op.f('ix_images_id'), 'images', ['id'], unique=True)
    op.drop_index('ix_images_image_url', table_name='images')
    op.create_index(op.f('ix_images_image_url'), 'images', ['image_url'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_images_image_url'), table_name='images')
    op.create_index('ix_images_image_url', 'images', ['image_url'], unique=1)
    op.drop_index(op.f('ix_images_id'), table_name='images')
    op.drop_column('images', 'image_full')
    # ### end Alembic commands ###
